# This workflow will install Python dependencies, run tests and lint with a variety of OSs.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: OS versions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os-version: ["ubuntu-latest", "macos-latest", "windows-latest"]

    runs-on: ${{ matrix.os-version }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install .[dev]
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . 
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 .
    - name: Test with pytest
      run: |
        pytest
